spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:   # sua app password do Google
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

  thymeleaf:
    enable: true

envio:
  email:
    remetente: jefersonguedes89@gmail.com
    nomeRemetente: 'Jeferson Guedes'

server:
  port: 8082





